// Client-side helpers for the upload paths that proxy through a Next.js route
// (/api/stores/upload, POST /api/admin/r2-upload).
//
// Two hazards those paths share:
//
// 1. Vercel caps a function's REQUEST BODY at ~4.5 MB on every plan. A modern phone
//    photo is routinely 4–12 MB, so an untouched camera shot fails. The failure is
//    generated by the platform, not the route, so the body is the plain string
//    "Request Entity Too Large" — and any caller that does res.json() on it dies with
//    `Unexpected token 'R', "Request En"... is not valid JSON`, which tells the user
//    nothing. Downscaling before upload avoids the cap entirely.
//
// 2. Even when it isn't a 413, an error body is not guaranteed to be JSON (gateway
//    timeouts, HTML error pages). Parse defensively, always.
//
// Files that legitimately exceed the cap (video, large media) must not use this — they
// belong on the presigned-PUT path (GET /api/admin/r2-upload), which uploads browser →
// R2 directly and has no such limit. See CLAUDE.md.

/** Hard ceiling for anything sent through a proxy route, with headroom under the
 *  ~4.5 MB platform cap for multipart overhead. */
export const PROXY_UPLOAD_LIMIT_BYTES = 4 * 1024 * 1024;

/**
 * Downscales an image in the browser so a phone photo fits comfortably through a proxy
 * route. Returns the original file untouched if it is already small, not an image, or
 * if anything goes wrong — callers still get a usable File either way.
 *
 * 1600px on the long edge is plenty for a document/label photo and for site imagery at
 * the sizes we render; it takes a typical 8 MB camera shot to roughly 300–600 KB.
 */
export async function compressImageFile(
  file: File,
  { maxEdge = 1600, quality = 0.82 }: { maxEdge?: number; quality?: number } = {},
): Promise<File> {
  if (!file.type.startsWith('image/')) return file;
  // Leave small files alone — recompressing costs quality for no benefit.
  if (file.size <= 600 * 1024) return file;
  // Canvas cannot round-trip an animated GIF or an SVG without destroying it.
  if (file.type === 'image/gif' || file.type === 'image/svg+xml') return file;

  try {
    const bitmap = await createImageBitmap(file);
    const scale  = Math.min(1, maxEdge / Math.max(bitmap.width, bitmap.height));
    const w = Math.round(bitmap.width * scale);
    const h = Math.round(bitmap.height * scale);

    const canvas = document.createElement('canvas');
    canvas.width = w; canvas.height = h;
    const ctx = canvas.getContext('2d');
    if (!ctx) return file;
    ctx.drawImage(bitmap, 0, 0, w, h);
    bitmap.close?.();

    const blob = await new Promise<Blob | null>((resolve) =>
      canvas.toBlob(resolve, 'image/jpeg', quality),
    );
    if (!blob || blob.size >= file.size) return file; // no gain — keep the original

    const name = file.name.replace(/\.[^.]+$/, '') + '.jpg';
    return new File([blob], name, { type: 'image/jpeg', lastModified: Date.now() });
  } catch {
    return file;
  }
}

/**
 * Reads a fetch Response that is *supposed* to be JSON without exploding when it
 * isn't. Returns the parsed body on success; throws an Error carrying a message a
 * human can act on otherwise.
 */
export async function readJsonOrThrow<T>(res: Response): Promise<T> {
  const text = await res.text().catch(() => '');

  if (!res.ok) {
    // The platform's body-size rejection arrives as plain text from the edge, before
    // the route ever runs, so there is no JSON error field to read.
    if (res.status === 413 || /request entity too large/i.test(text)) {
      throw new Error('That file is too large to upload. Please use an image under 4 MB.');
    }
    let msg = text.trim();
    try { msg = (JSON.parse(text) as { error?: string }).error ?? msg; } catch { /* not JSON */ }
    // An HTML error page is noise — show the status instead of dumping markup.
    if (!msg || msg.startsWith('<')) msg = `Upload failed (${res.status})`;
    throw new Error(msg.slice(0, 300));
  }

  try {
    return JSON.parse(text) as T;
  } catch {
    throw new Error('The server returned an unexpected response. Please try again.');
  }
}
