import { Logo } from '@/components/icons/logo';

const sections = [
  {
    id: 'overview',
    title: 'Agreement Overview',
    content: `These Terms of Service ("Terms") constitute a legally binding agreement between ALIVE Advertising Pvt. Ltd. ("ALIVE," "we," "us," or "our") and any individual, business entity, kirana store owner, or brand partner ("you" or "User") who accesses or uses our platform, services, digital screens, or any related offerings.

By installing ALIVE equipment, accessing our dashboard, running campaigns, or engaging with our services in any capacity, you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, please do not use our services.`,
  },
  {
    id: 'definitions',
    title: '1. Definitions',
    items: [
      { term: '"Platform"', def: 'ALIVE\'s web and mobile-based dashboard, backend systems, Android TV application, and all associated software used for campaign management and reporting.' },
      { term: '"Store Partner"', def: 'A kirana store owner or retail outlet that has entered into a separate Store Partnership Agreement with ALIVE to host digital screens on their premises.' },
      { term: '"Brand Partner"', def: 'A company, agency, or advertiser that has entered into a Campaign Agreement with ALIVE to display advertisements through the ALIVE network.' },
      { term: '"Screen"', def: 'The digital display hardware installed by ALIVE at a Store Partner location.' },
      { term: '"Campaign"', def: 'A set of advertisements, creatives, and targeting parameters configured by a Brand Partner for display on ALIVE Screens.' },
      { term: '"Proof-of-Play"', def: 'The verified impression data generated by ALIVE\'s system to confirm that a Campaign creative was displayed on a Screen at a given time.' },
      { term: '"Content"', def: 'Any advertisement, image, video, text, logo, or media submitted by a Brand Partner for display through the Platform.' },
    ],
  },
  {
    id: 'eligibility',
    title: '2. Eligibility and Account Registration',
    subsections: [
      {
        heading: '2.1 Eligibility',
        text: 'To use ALIVE\'s services, you must: (a) be at least 18 years of age; (b) have the legal capacity to enter into binding contracts under applicable Indian law; and (c) comply with all applicable laws and regulations.',
      },
      {
        heading: '2.2 Account Registration',
        text: 'Store Partners and Brand Partners must register an account on the Platform. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.',
      },
      {
        heading: '2.3 Account Security',
        text: 'You must immediately notify ALIVE at contact@alivemedia.in if you suspect any unauthorized use of your account. ALIVE shall not be liable for any loss arising from unauthorized use of your account due to your failure to maintain the security of your credentials.',
      },
    ],
  },
  {
    id: 'store-partners',
    title: '3. Store Partner Terms',
    subsections: [
      {
        heading: '3.1 Equipment Installation',
        text: 'ALIVE will arrange installation of digital Screens and supporting hardware at your store premises as agreed in your Store Partnership Agreement. You grant ALIVE and its authorized representatives a non-exclusive right to access your premises for installation, maintenance, repair, and removal of equipment.',
      },
      {
        heading: '3.2 Store Partner Obligations',
        bullets: [
          'Provide a suitable wall space, power supply, and internet connectivity as specified by ALIVE.',
          'Ensure Screens remain powered on and operational during agreed store operating hours.',
          'Not tamper with, modify, relocate, or obstruct the Screens or associated hardware.',
          'Not display any third-party advertising content on ALIVE Screens without ALIVE\'s prior written consent.',
          'Promptly notify ALIVE of any damage, malfunction, or security concern relating to the Screens.',
          'Allow ALIVE to perform remote diagnostics, software updates, and content management on the Screens.',
        ],
      },
      {
        heading: '3.3 Revenue Sharing',
        text: 'Store Partners will receive a monthly revenue share as specified in the Store Partnership Agreement. Payments are subject to the Screens being operational and meeting minimum uptime thresholds as defined therein. ALIVE reserves the right to deduct amounts for periods of downtime caused by Store Partner actions or negligence.',
      },
      {
        heading: '3.4 Equipment Ownership',
        text: 'All Screens, hardware, and software installed by ALIVE remain the exclusive property of ALIVE at all times. Upon termination of the Store Partnership Agreement, ALIVE reserves the right to remove all equipment from your premises within a reasonable timeframe.',
      },
    ],
  },
  {
    id: 'brand-partners',
    title: '4. Brand Partner Terms',
    subsections: [
      {
        heading: '4.1 Campaign Submission',
        text: 'Brand Partners may submit Campaigns through the Platform subject to these Terms and any applicable Campaign Agreement. By submitting Content, you represent and warrant that: (a) you own or have all necessary rights, licences, and consents to use the Content; (b) the Content does not infringe any third-party intellectual property rights; and (c) the Content complies with all applicable laws including advertising standards.',
      },
      {
        heading: '4.2 Content Standards',
        text: 'ALIVE reserves the right to reject, modify, or remove any Content that:',
        bullets: [
          'Promotes illegal products, services, or activities under Indian law.',
          'Contains misleading, deceptive, or false advertising claims.',
          'Is obscene, offensive, discriminatory, or otherwise inappropriate for a general retail audience.',
          'Violates the Advertising Standards Council of India (ASCI) guidelines.',
          'Infringes upon intellectual property rights of any third party.',
          'Promotes products regulated under the Drugs and Magic Remedies Act, tobacco products, or alcohol without appropriate approvals.',
        ],
      },
      {
        heading: '4.3 Campaign Delivery and Proof-of-Play',
        text: 'ALIVE will use reasonable efforts to deliver Campaigns as scheduled. Campaign delivery is subject to network availability, screen uptime, and operational conditions. ALIVE provides Proof-of-Play reports as evidence of delivery; however, these are estimates based on system logs and do not constitute a guarantee of exact impression counts. In case of significant shortfalls, ALIVE will offer make-good credits as per the Campaign Agreement.',
      },
      {
        heading: '4.4 Payment Terms',
        text: 'Campaign fees are payable as per the Campaign Agreement. ALIVE reserves the right to suspend active Campaigns in the event of non-payment. All fees are exclusive of applicable taxes including GST, which shall be borne by the Brand Partner. Invoices are issued monthly and are due within 15 days of the invoice date unless otherwise agreed.',
      },
    ],
  },
  {
    id: 'ip',
    title: '5. Intellectual Property',
    subsections: [
      {
        heading: '5.1 ALIVE\'s Intellectual Property',
        text: 'The ALIVE Platform, technology, algorithms, trade dress, brand name, logo, and all related materials are the exclusive intellectual property of ALIVE Advertising Pvt. Ltd. Nothing in these Terms grants you any ownership or licence to ALIVE\'s intellectual property except as expressly required to use the services.',
      },
      {
        heading: '5.2 Brand Partner Content Licence',
        text: 'By submitting Content, Brand Partners grant ALIVE a non-exclusive, royalty-free, worldwide licence to display, reproduce, and distribute such Content solely for the purpose of delivering the contracted Campaign. This licence terminates upon Campaign completion or termination of the Campaign Agreement.',
      },
      {
        heading: '5.3 Feedback and Suggestions',
        text: 'Any feedback, suggestions, or recommendations you provide to ALIVE regarding the Platform or services may be used by ALIVE without restriction or compensation to you.',
      },
    ],
  },
  {
    id: 'data',
    title: '6. Data and Analytics',
    content: 'ALIVE collects aggregated, anonymised audience and campaign performance data through its Platform. ALIVE may use this data to improve its services, generate industry insights, and for marketing purposes. Data shared with Brand Partners in reports will be aggregated and will not identify individual shoppers. For details on personal data processing, please refer to ALIVE\'s Privacy Policy.',
  },
  {
    id: 'liability',
    title: '7. Limitation of Liability',
    bullets: [
      'ALIVE\'s total liability to any User in connection with these Terms shall not exceed the amounts paid to or by such User in the three (3) months preceding the event giving rise to the claim.',
      'ALIVE shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, revenue, data, or goodwill.',
      'ALIVE does not guarantee uninterrupted or error-free operation of the Platform or Screens. Outages due to internet connectivity, power failures, force majeure events, or third-party service failures are expressly excluded from liability.',
      'Nothing in these Terms shall exclude or limit liability for death or personal injury caused by negligence, or for fraud or fraudulent misrepresentation.',
    ],
  },
  {
    id: 'indemnification',
    title: '8. Indemnification',
    content: 'You agree to indemnify, defend, and hold harmless ALIVE and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or relating to: (a) your use of the Platform or services; (b) your violation of these Terms; (c) your Content or its infringement of third-party rights; or (d) your violation of applicable laws.',
  },
  {
    id: 'termination',
    title: '9. Term and Termination',
    subsections: [
      { heading: '9.1 Term', text: 'These Terms remain in effect for as long as you use ALIVE\'s services or maintain an account on the Platform.' },
      { heading: '9.2 Termination by User', text: 'Store Partners may terminate their Store Partnership Agreement as per the notice period specified therein. Brand Partners may cancel scheduled Campaigns subject to the cancellation policy in the Campaign Agreement.' },
      { heading: '9.3 Termination by ALIVE', text: 'ALIVE may suspend or terminate your access to the Platform or services, with or without notice, if: (a) you breach these Terms or any associated agreement; (b) you engage in fraudulent or unlawful activity; or (c) continued service is commercially unviable. Upon termination, ALIVE will settle outstanding payments in accordance with applicable agreements.' },
    ],
  },
  {
    id: 'governing-law',
    title: '10. Governing Law and Dispute Resolution',
    content: 'These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts at Mangalore, Karnataka, India.\n\nPrior to initiating legal proceedings, the parties agree to attempt resolution through good-faith negotiation for a period of 30 days. If unresolved, disputes shall be referred to arbitration under the Arbitration and Conciliation Act, 1996, with a single arbitrator appointed by mutual consent.',
  },
  {
    id: 'miscellaneous',
    title: '11. Miscellaneous',
    items: [
      { term: 'Entire Agreement', def: 'These Terms, together with applicable Partnership Agreements and the Privacy Policy, constitute the entire agreement between you and ALIVE with respect to the subject matter hereof.' },
      { term: 'Amendments', def: 'ALIVE reserves the right to update these Terms at any time. Material changes will be communicated via email or Platform notification with at least 14 days\' notice. Continued use of services constitutes acceptance of the revised Terms.' },
      { term: 'Severability', def: 'If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will continue in full force and effect.' },
      { term: 'Waiver', def: 'ALIVE\'s failure to enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.' },
      { term: 'Force Majeure', def: 'ALIVE shall not be liable for failures or delays caused by circumstances beyond its reasonable control including natural disasters, government actions, or internet outages.' },
      { term: 'Assignment', def: 'You may not assign your rights or obligations under these Terms without ALIVE\'s prior written consent. ALIVE may freely assign its rights.' },
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="sticky top-0 z-50 border-b border-border/30 bg-background/95 backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4 sm:px-6">
          <a href="/" className="opacity-70 hover:opacity-100 transition-opacity"><Logo /></a>
          <a href="/privacy" className="text-xs text-muted-foreground hover:text-foreground transition-colors">Privacy Policy →</a>
        </div>
      </header>

      <main className="flex-1 mx-auto w-full max-w-3xl px-4 sm:px-6 py-12 sm:py-16">
        {/* Header */}
        <div className="mb-12 space-y-3 border-b border-border pb-10">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Legal</p>
          <h1 className="text-4xl font-bold tracking-tight text-foreground">Terms of Service</h1>
          <p className="text-sm text-muted-foreground">Governing Use of ALIVE Platform &amp; Services</p>
          <div className="flex flex-wrap gap-x-6 gap-y-1 pt-2 text-xs text-muted-foreground/70">
            <span><strong className="text-muted-foreground">Effective date:</strong> May 1, 2025</span>
            <span><strong className="text-muted-foreground">Company:</strong> ALIVE Advertising Pvt. Ltd.</span>
            <span><strong className="text-muted-foreground">Location:</strong> Mangaluru, Karnataka, India</span>
            <span><strong className="text-muted-foreground">Email:</strong> legal@alivemedia.in</span>
          </div>
        </div>

        {/* Sections */}
        <div className="space-y-10 text-sm leading-relaxed text-muted-foreground">
          {sections.map((s) => (
            <section key={s.id} id={s.id}>
              <h2 className="text-base font-bold text-foreground mb-3">{s.title}</h2>

              {'content' in s && s.content && (
                <div className="space-y-3">
                  {s.content.split('\n\n').map((p, i) => (
                    <p key={i}>{p}</p>
                  ))}
                </div>
              )}

              {'items' in s && s.items && (
                <dl className="space-y-3">
                  {s.items.map((item) => (
                    <div key={item.term} className="flex gap-2">
                      <dt className="shrink-0 font-semibold text-foreground">{item.term}</dt>
                      <dd>— {item.def}</dd>
                    </div>
                  ))}
                </dl>
              )}

              {'bullets' in s && s.bullets && (
                <ul className="space-y-2 pl-4">
                  {s.bullets.map((b, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary/60" />
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              )}

              {'subsections' in s && s.subsections && (
                <div className="space-y-5">
                  {s.subsections.map((sub) => (
                    <div key={sub.heading}>
                      <h3 className="font-semibold text-foreground text-[13px] mb-1.5">{sub.heading}</h3>
                      {'text' in sub && sub.text && <p>{sub.text}</p>}
                      {'bullets' in sub && sub.bullets && (
                        <ul className="mt-2 space-y-1.5 pl-4">
                          {sub.bullets.map((b, i) => (
                            <li key={i} className="flex gap-2">
                              <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary/60" />
                              <span>{b}</span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </section>
          ))}

          {/* Contact */}
          <section id="contact" className="rounded-xl border border-border bg-card p-6 space-y-3">
            <h2 className="text-base font-bold text-foreground">12. Contact Information</h2>
            <p>For any queries regarding these Terms, please contact:</p>
            <div className="text-foreground space-y-0.5 font-medium">
              <p>ALIVE Advertising Pvt. Ltd.</p>
              <p className="text-muted-foreground font-normal">Mangaluru, Karnataka, India</p>
              <p>Email: <a href="mailto:legal@alivemedia.in" className="text-primary hover:underline">legal@alivemedia.in</a></p>
              <p>Website: <a href="https://www.alivemedia.in" className="text-primary hover:underline">www.alivemedia.in</a></p>
            </div>
          </section>
        </div>
      </main>

      <footer className="border-t border-border/30 py-6 text-center">
        <p className="text-xs text-muted-foreground/40">
          © 2025 ALIVE Advertising Pvt. Ltd. · Mangaluru, Karnataka, India
        </p>
      </footer>
    </div>
  );
}
